version: '3.8'

services:
  php-apache-app:
    container_name: "php-apache-app"
    build: .
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - './html:/var/www/html'
    restart: always
  
  mysql-app:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '010203'