version: '3.9'

networks:
  ws-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          
services:
  php-apache:
    image: php:8.1-apache
    build: .
    networks:
      ws-network:
        ipv4_address: 10.0.0.2
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html

  composer:
    image: composer/composer
    command: 'composer install'
    volumes:
      - ./html:/app
    depends_on:
      - php-apache

  mysql:
    image: mysql:latest
    networks:
      ws-network:
        ipv4_address: 10.0.0.3
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'America/Sao_Paulo'
    restart: always
    volumes:
      - ./db:/var/lib/mysql