insert into address (id, street, city, state, zip) values (1, 'Clemons', 'Saint Louis', 'Missouri', '07-990-6879');
insert into address (id, street, city, state, zip) values (2, 'Kenwood', 'Paulínia', null, '78-050-1484');
insert into address (id, street, city, state, zip) values (3, 'Steensland', 'Dongobesh', null, '40-536-5682');
insert into address (id, street, city, state, zip) values (4, 'Waubesa', 'Gunungkoneng', null, '06-310-3273');
insert into address (id, street, city, state, zip) values (5, 'Bluestem', 'Promissão', null, '03-284-1004');
insert into address (id, street, city, state, zip) values (6, '3rd', 'Golovchino', null, '52-368-2972');
insert into address (id, street, city, state, zip) values (7, 'Arkansas', 'Zhangjiachang', null, '05-768-3713');
insert into address (id, street, city, state, zip) values (8, 'Marcy', 'Arapiraca', null, '34-929-5054');
insert into address (id, street, city, state, zip) values (9, 'Kings', 'Antiguo Cuscatlán', null, '91-990-9562');
insert into address (id, street, city, state, zip) values (10, 'Farragut', 'Az̧ Z̧alī‘ah', null, '13-158-6246');
insert into address (id, street, city, state, zip) values (11, 'Nancy', 'Kyurdarmir', null, '87-735-6554');
insert into address (id, street, city, state, zip) values (12, 'Welch', 'Fonte do Feto', 'Setúbal', '56-623-0878');
insert into address (id, street, city, state, zip) values (13, 'Melvin', 'Bocaiúva', null, '11-378-9068');
insert into address (id, street, city, state, zip) values (14, 'Grim', 'Dingzhai', null, '92-151-6281');
insert into address (id, street, city, state, zip) values (15, 'Kennedy', 'New Haven', 'Connecticut', '14-355-2960');
insert into address (id, street, city, state, zip) values (16, 'Buena Vista', 'Domampot', null, '69-318-2300');
insert into address (id, street, city, state, zip) values (17, 'Schurz', 'Wawrzeńczyce', null, '01-326-5380');
insert into address (id, street, city, state, zip) values (18, 'Havey', 'Tuchengzi', null, '13-869-5228');
insert into address (id, street, city, state, zip) values (19, 'Red Cloud', 'Banī Ḩassān', null, '99-709-7747');
insert into address (id, street, city, state, zip) values (20, 'Holy Cross', 'Necochea', null, '06-019-6308');
insert into address (id, street, city, state, zip) values (21, 'Green Ridge', 'Osek nad Bečvou', null, '24-730-5964');
insert into address (id, street, city, state, zip) values (22, 'Northport', 'Beit Horon', null, '44-449-6098');
insert into address (id, street, city, state, zip) values (23, 'Linden', 'Kalidawe', null, '71-714-8530');
insert into address (id, street, city, state, zip) values (24, 'Luster', 'Cametá', null, '40-394-5416');
insert into address (id, street, city, state, zip) values (25, 'Redwing', 'Anton', null, '49-907-7724');
insert into address (id, street, city, state, zip) values (26, 'Spenser', 'Arroyito', null, '84-667-4708');
insert into address (id, street, city, state, zip) values (27, 'Harper', 'Bojnik', null, '46-451-4110');
insert into address (id, street, city, state, zip) values (28, 'Cordelia', 'Banjar Penyalin', null, '27-080-9418');
insert into address (id, street, city, state, zip) values (29, 'Fulton', 'Maulavi Bāzār', null, '33-892-2897');
insert into address (id, street, city, state, zip) values (30, 'Vahlen', 'Skomlin', null, '52-444-6102');
insert into address (id, street, city, state, zip) values (31, 'Memorial', 'Sūrāb', null, '39-619-0246');
insert into address (id, street, city, state, zip) values (32, 'Oak', 'Bayān', null, '72-947-7262');
insert into address (id, street, city, state, zip) values (33, 'Heath', 'Atsugi', null, '00-164-5161');
insert into address (id, street, city, state, zip) values (34, 'Brown', 'Baitu', null, '17-906-7215');
insert into address (id, street, city, state, zip) values (35, 'Arkansas', 'Bol’shoye Skuratovo', null, '44-077-9110');
insert into address (id, street, city, state, zip) values (36, 'Waxwing', 'Yufa', null, '22-595-3734');
insert into address (id, street, city, state, zip) values (37, 'Bayside', 'Ndjolé', null, '46-151-1557');
insert into address (id, street, city, state, zip) values (38, 'Melby', 'Bailai', null, '97-526-3692');
insert into address (id, street, city, state, zip) values (39, 'Kingsford', 'Huambo', null, '13-438-3853');
insert into address (id, street, city, state, zip) values (40, 'Clove', 'Pa Tio', null, '81-163-8935');
insert into address (id, street, city, state, zip) values (41, 'Pawling', 'Sok Kwu Wan', null, '52-697-2393');
insert into address (id, street, city, state, zip) values (42, 'Rowland', 'Xiaruyue', null, '94-002-2077');
insert into address (id, street, city, state, zip) values (43, 'Talisman', 'Neyvo-Rudyanka', null, '99-663-0057');
insert into address (id, street, city, state, zip) values (44, 'Marcy', 'Murmino', null, '78-607-8806');
insert into address (id, street, city, state, zip) values (45, 'Summit', 'Nikkō', null, '09-324-8693');
insert into address (id, street, city, state, zip) values (46, 'Namekagon', 'Arboleda', null, '59-162-7394');
insert into address (id, street, city, state, zip) values (47, 'Shopko', 'Guia', 'Faro', '05-128-0071');
insert into address (id, street, city, state, zip) values (48, 'Arizona', 'Oliveirinha', 'Viseu', '15-969-4939');
insert into address (id, street, city, state, zip) values (49, 'Manley', 'Jinqiao', null, '85-394-9726');
insert into address (id, street, city, state, zip) values (50, 'Spaight', 'Outapi', null, '39-405-7575');
insert into address (id, street, city, state, zip) values (51, 'Merchant', 'Huddinge', 'Stockholm', '38-840-0071');
insert into address (id, street, city, state, zip) values (52, 'Nevada', 'Karagach', null, '15-249-6406');
insert into address (id, street, city, state, zip) values (53, 'Glacier Hill', 'Furmanov', null, '70-156-8137');
insert into address (id, street, city, state, zip) values (54, 'Buena Vista', 'Nashville', 'Tennessee', '99-102-8095');
insert into address (id, street, city, state, zip) values (55, 'Derek', 'Pocrí', null, '90-404-2651');
insert into address (id, street, city, state, zip) values (56, 'Golf View', 'Lunik', null, '56-851-3862');
insert into address (id, street, city, state, zip) values (57, 'Drewry', 'Gävle', 'Gävleborg', '34-687-3815');
insert into address (id, street, city, state, zip) values (58, 'Texas', 'La Concepcion', 'Mexico', '05-008-4487');
insert into address (id, street, city, state, zip) values (59, 'Anthes', 'Tianta', null, '47-108-2941');
insert into address (id, street, city, state, zip) values (60, 'Golf', 'Calabaca', null, '44-397-6578');
insert into address (id, street, city, state, zip) values (61, 'Warner', 'Zhongshan Donglu', null, '42-614-2953');
insert into address (id, street, city, state, zip) values (62, 'Starling', 'San Antonio', null, '47-918-4404');
insert into address (id, street, city, state, zip) values (63, 'Dennis', 'Lancaster', 'California', '89-456-8239');
insert into address (id, street, city, state, zip) values (64, 'Jay', 'Yanwang', null, '28-329-9059');
insert into address (id, street, city, state, zip) values (65, 'Dahle', 'Huotong', null, '32-088-9530');
insert into address (id, street, city, state, zip) values (66, 'Coleman', 'San Francisco', 'Jalisco', '09-161-2286');
insert into address (id, street, city, state, zip) values (67, 'Manitowish', 'Bojonglarang', null, '39-207-9016');
insert into address (id, street, city, state, zip) values (68, 'Bowman', 'Montenegro', null, '46-922-4498');
insert into address (id, street, city, state, zip) values (69, 'Sugar', 'Jianshan', null, '59-485-9290');
insert into address (id, street, city, state, zip) values (70, 'Huxley', 'Tianmuhu', null, '43-127-2155');
insert into address (id, street, city, state, zip) values (71, 'Monument', 'Huelkail', null, '93-109-3134');
insert into address (id, street, city, state, zip) values (72, 'Clarendon', 'São Sebastião do Passé', null, '06-708-1579');
insert into address (id, street, city, state, zip) values (73, 'Debs', 'Cojata', null, '96-574-1165');
insert into address (id, street, city, state, zip) values (74, 'Briar Crest', 'Thorold', 'Ontario', '42-538-3417');
insert into address (id, street, city, state, zip) values (75, 'Pleasure', 'Melbourne', 'Victoria', '99-826-9434');
insert into address (id, street, city, state, zip) values (76, 'Almo', 'Citangtu Kaler', null, '77-771-1112');
insert into address (id, street, city, state, zip) values (77, 'Derek', 'Nishor', null, '94-352-7809');
insert into address (id, street, city, state, zip) values (78, 'Texas', 'Havana', null, '43-818-2497');
insert into address (id, street, city, state, zip) values (79, 'Sutteridge', 'Tasböget', null, '61-987-9607');
insert into address (id, street, city, state, zip) values (80, 'Kropf', 'San Luis Jilotepeque', null, '19-136-8906');
insert into address (id, street, city, state, zip) values (81, 'Haas', 'Gia Ray', null, '42-312-5407');
insert into address (id, street, city, state, zip) values (82, 'Lighthouse Bay', 'Haugesund', 'Rogaland', '79-903-1952');
insert into address (id, street, city, state, zip) values (83, 'Randy', 'Sanxiang', null, '39-119-1660');
insert into address (id, street, city, state, zip) values (84, 'Paget', 'Yanzhao', null, '38-481-1668');
insert into address (id, street, city, state, zip) values (85, 'Shopko', 'Leipzig', 'Sachsen', '83-902-0506');
insert into address (id, street, city, state, zip) values (86, 'Acker', 'Francova Lhota', null, '77-811-6221');
insert into address (id, street, city, state, zip) values (87, 'Loftsgordon', 'Gongpo', null, '94-619-6894');
insert into address (id, street, city, state, zip) values (88, 'Cardinal', 'Tsákoi', null, '19-854-7470');
insert into address (id, street, city, state, zip) values (89, 'Bashford', 'Novopokrovskaya', null, '55-948-6776');
insert into address (id, street, city, state, zip) values (90, 'Glacier Hill', 'Debelets', null, '73-861-6621');
insert into address (id, street, city, state, zip) values (91, 'Petterle', 'Meikeng', null, '52-514-4113');
insert into address (id, street, city, state, zip) values (92, 'Ridgeview', 'Malaba', null, '86-696-3626');
insert into address (id, street, city, state, zip) values (93, 'Lakewood Gardens', 'Valence', 'Rhône-Alpes', '21-043-4927');
insert into address (id, street, city, state, zip) values (94, 'Vidon', 'Lees Summit', 'Missouri', '68-645-1640');
insert into address (id, street, city, state, zip) values (95, 'Larry', 'Banjar Bali', null, '68-375-4591');
insert into address (id, street, city, state, zip) values (96, 'Forest Dale', 'Hengxizhen', null, '17-920-6454');
insert into address (id, street, city, state, zip) values (97, 'Dennis', 'Summerside', 'Prince Edward Island', '48-742-4054');
insert into address (id, street, city, state, zip) values (98, 'Tomscot', 'Tcholliré', null, '99-185-9318');
insert into address (id, street, city, state, zip) values (99, 'Hudson', 'Ust’-Labinsk', null, '90-587-4420');
insert into address (id, street, city, state, zip) values (100, 'Twin Pines', 'Roberval', 'Québec', '36-479-0269');
