insert into address (id, street, city, state, zip) values (1, 'Lukken', 'Biancheng', null, '405');
insert into address (id, street, city, state, zip) values (2, 'Esch', 'Tanggeung Kolot', null, '628');
insert into address (id, street, city, state, zip) values (3, 'Lunder', 'Ullubiyaul', null, '3');
insert into address (id, street, city, state, zip) values (4, 'Thackeray', 'Forécariah', null, '91');
insert into address (id, street, city, state, zip) values (5, 'Kings', 'Gorzów Wielkopolski', null, '217');
insert into address (id, street, city, state, zip) values (6, 'Mesta', 'Miches', null, '257');
insert into address (id, street, city, state, zip) values (7, 'Pearson', 'Limbaan', null, '9111');
insert into address (id, street, city, state, zip) values (8, 'Rusk', 'Dewetsdorp', null, '94136');
insert into address (id, street, city, state, zip) values (9, 'Sherman', 'Santi Suk', null, '45297');
insert into address (id, street, city, state, zip) values (10, 'Victoria', 'Litian', null, '81654');
insert into address (id, street, city, state, zip) values (11, 'Menomonie', 'Kāleke Mandi', null, '54857');
insert into address (id, street, city, state, zip) values (12, 'Center', 'Tsukawaki', null, '0');
insert into address (id, street, city, state, zip) values (13, 'Oak', 'Arruda dos Vinhos', 'Lisboa', '575');
insert into address (id, street, city, state, zip) values (14, 'Swallow', 'Angoulême', 'Poitou-Charentes', '52810');
insert into address (id, street, city, state, zip) values (15, 'Starling', 'Lang Suan', null, '964');
insert into address (id, street, city, state, zip) values (16, 'Elgar', 'Anshun', null, '073');
insert into address (id, street, city, state, zip) values (17, 'Ridgeway', 'Jinkou', null, '5');
insert into address (id, street, city, state, zip) values (18, 'Forster', 'Usogorsk', null, '580');
insert into address (id, street, city, state, zip) values (19, 'Cardinal', 'Pribrezhnyy', null, '6');
insert into address (id, street, city, state, zip) values (20, 'Hooker', 'Stod', null, '55');
insert into address (id, street, city, state, zip) values (21, 'Muir', 'Kelaniya', null, '474');
insert into address (id, street, city, state, zip) values (22, 'Ohio', 'Sarov', null, '05967');
insert into address (id, street, city, state, zip) values (23, 'Elgar', 'Sult', null, '47744');
insert into address (id, street, city, state, zip) values (24, 'Daystar', 'Platičevo', null, '91269');
insert into address (id, street, city, state, zip) values (25, 'Heffernan', 'Shangbahe', null, '7');
insert into address (id, street, city, state, zip) values (26, 'Heffernan', 'Manzurka', null, '758');
insert into address (id, street, city, state, zip) values (27, 'Lighthouse Bay', 'Fankeng', null, '3');
insert into address (id, street, city, state, zip) values (28, 'Dakota', 'Allada', null, '37517');
insert into address (id, street, city, state, zip) values (29, 'Blaine', 'Jinzhuang', null, '9855');
insert into address (id, street, city, state, zip) values (30, 'Stephen', 'Ganping', null, '37');
insert into address (id, street, city, state, zip) values (31, 'Butternut', 'Pereiro', 'Viana do Castelo', '76098');
insert into address (id, street, city, state, zip) values (32, 'Dottie', 'Dzhubga', null, '0079');
insert into address (id, street, city, state, zip) values (33, 'Forest Dale', 'Tingloy', null, '743');
insert into address (id, street, city, state, zip) values (34, 'Victoria', 'Pinhal de Frades', 'Setúbal', '99818');
insert into address (id, street, city, state, zip) values (35, 'Beilfuss', 'Meilin', null, '4722');
insert into address (id, street, city, state, zip) values (36, 'Marcy', 'Tokarnia', null, '69137');
insert into address (id, street, city, state, zip) values (37, 'Waywood', 'Yangtan', null, '51');
insert into address (id, street, city, state, zip) values (38, 'Onsgard', 'Bagorejo', null, '6179');
insert into address (id, street, city, state, zip) values (39, 'Logan', 'Viñac', null, '2074');
insert into address (id, street, city, state, zip) values (40, 'Eastwood', 'Vessada', 'Aveiro', '68867');
insert into address (id, street, city, state, zip) values (41, 'Division', 'Beijie', null, '6');
insert into address (id, street, city, state, zip) values (42, 'Knutson', 'Subic', null, '9835');
insert into address (id, street, city, state, zip) values (43, 'Helena', 'Bancroft', 'Ontario', '63');
insert into address (id, street, city, state, zip) values (44, 'Independence', 'Mosul', null, '2');
insert into address (id, street, city, state, zip) values (45, 'Elka', 'Petrovo-Dal’neye', null, '0577');
insert into address (id, street, city, state, zip) values (46, 'Maywood', 'Stockholm', 'Stockholm', '6');
insert into address (id, street, city, state, zip) values (47, 'Melody', 'Guane', null, '68794');
insert into address (id, street, city, state, zip) values (48, 'Farragut', 'Grande Rivière du Nord', null, '934');
insert into address (id, street, city, state, zip) values (49, 'Amoth', 'Farriar', null, '7');
insert into address (id, street, city, state, zip) values (50, 'Lakewood', 'Takikawa', null, '43150');
insert into address (id, street, city, state, zip) values (51, 'Hanson', 'Heshi', null, '8');
insert into address (id, street, city, state, zip) values (52, 'Northridge', 'Bueng Kum', null, '89448');
insert into address (id, street, city, state, zip) values (53, 'Kingsford', 'Waepana', null, '5239');
insert into address (id, street, city, state, zip) values (54, 'Memorial', 'Kitami', null, '53');
insert into address (id, street, city, state, zip) values (55, 'Drewry', 'Sanqu', null, '8552');
insert into address (id, street, city, state, zip) values (56, 'Dapin', 'Vřesina', null, '088');
insert into address (id, street, city, state, zip) values (57, 'Vermont', 'San Agustín Acasaguastlán', null, '506');
insert into address (id, street, city, state, zip) values (58, 'Kropf', 'Livádion', null, '533');
insert into address (id, street, city, state, zip) values (59, 'New Castle', 'Chantilly', 'Picardie', '8519');
insert into address (id, street, city, state, zip) values (60, 'Anzinger', 'Wleń', null, '69659');
insert into address (id, street, city, state, zip) values (61, 'Mendota', 'Donggaocun', null, '7156');
insert into address (id, street, city, state, zip) values (62, 'Eliot', 'Gakem', null, '41189');
insert into address (id, street, city, state, zip) values (63, 'Orin', 'Shangtianba', null, '563');
insert into address (id, street, city, state, zip) values (64, 'High Crossing', 'Norrköping', 'Östergötland', '6883');
insert into address (id, street, city, state, zip) values (65, 'Welch', 'Cansolungon', null, '464');
insert into address (id, street, city, state, zip) values (66, 'Schmedeman', 'Iraray', null, '3');
insert into address (id, street, city, state, zip) values (67, 'New Castle', 'Saint-Étienne', 'Rhône-Alpes', '206');
insert into address (id, street, city, state, zip) values (68, 'Tony', 'La Rochelle', 'Poitou-Charentes', '3936');
insert into address (id, street, city, state, zip) values (69, 'Warbler', 'Luleå', 'Norrbotten', '0');
insert into address (id, street, city, state, zip) values (70, 'Stuart', 'Chongjin', null, '8');
insert into address (id, street, city, state, zip) values (71, 'Vermont', 'Guinabsan', null, '36893');
insert into address (id, street, city, state, zip) values (72, 'Morningstar', 'Kremenets’', null, '44');
insert into address (id, street, city, state, zip) values (73, 'Talmadge', 'Tripoli', null, '52610');
insert into address (id, street, city, state, zip) values (74, 'Tennessee', 'Västerås', 'Västmanland', '5');
insert into address (id, street, city, state, zip) values (75, 'Charing Cross', 'Guji', null, '9');
insert into address (id, street, city, state, zip) values (76, 'Meadow Vale', 'Panadtaban', null, '016');
insert into address (id, street, city, state, zip) values (77, 'Hanover', 'Ludgeřovice', null, '6218');
insert into address (id, street, city, state, zip) values (78, 'Acker', 'Wujiabao', null, '56');
insert into address (id, street, city, state, zip) values (79, 'Oxford', 'Ajuda', 'Ilha de São Miguel', '9');
insert into address (id, street, city, state, zip) values (80, 'Debs', 'Talipan', null, '44193');
insert into address (id, street, city, state, zip) values (81, 'Meadow Ridge', 'Yong’an', null, '1');
insert into address (id, street, city, state, zip) values (82, 'Bobwhite', 'Varnsdorf', null, '137');
insert into address (id, street, city, state, zip) values (83, 'Center', 'Mazār-e Sharīf', null, '0');
insert into address (id, street, city, state, zip) values (84, 'Springs', 'Vĩnh Thuận', null, '3');
insert into address (id, street, city, state, zip) values (85, 'Logan', 'Tokombere', null, '6');
insert into address (id, street, city, state, zip) values (86, 'Mayer', 'Telouet', null, '39491');
insert into address (id, street, city, state, zip) values (87, 'Golf', 'Podedwórze', null, '9757');
insert into address (id, street, city, state, zip) values (88, 'Upham', 'Chambéry', 'Rhône-Alpes', '01348');
insert into address (id, street, city, state, zip) values (89, 'Basil', 'Stříbro', null, '35');
insert into address (id, street, city, state, zip) values (90, 'Dawn', 'Chimoio', null, '3');
insert into address (id, street, city, state, zip) values (91, 'Vernon', 'Bancak Wetan', null, '7662');
insert into address (id, street, city, state, zip) values (92, 'Jenifer', 'Načeradec', null, '1');
insert into address (id, street, city, state, zip) values (93, 'Messerschmidt', 'Evijärvi', null, '4308');
insert into address (id, street, city, state, zip) values (94, 'Bunting', 'Krajan Tengah', null, '74608');
insert into address (id, street, city, state, zip) values (95, 'Hooker', 'Medvedevo', null, '495');
insert into address (id, street, city, state, zip) values (96, 'Superior', 'Ust’-Labinsk', null, '156');
insert into address (id, street, city, state, zip) values (97, 'Chive', 'Mādabā', null, '3441');
insert into address (id, street, city, state, zip) values (98, 'Hovde', 'Barayong', null, '35');
insert into address (id, street, city, state, zip) values (99, 'Charing Cross', 'Bánov', null, '428');
insert into address (id, street, city, state, zip) values (100, 'Scott', 'Jinsha', null, '51178');
