insert into address (id, street, city, state, zip) values (1, 'Waubesa', 'Biru', null, null);
insert into address (id, street, city, state, zip) values (2, 'Maple Wood', 'Niort', 'Poitou-Charentes', '79083 CEDEX 9');
insert into address (id, street, city, state, zip) values (3, 'Brown', 'Ivanava', null, null);
insert into address (id, street, city, state, zip) values (4, 'Brown', 'Tuzhai', null, null);
insert into address (id, street, city, state, zip) values (5, 'Loomis', 'Santa Vitória do Palmar', null, '96230-000');
insert into address (id, street, city, state, zip) values (6, 'Northfield', 'Terenozek', null, null);
insert into address (id, street, city, state, zip) values (7, 'Banding', 'San Pedro Ayampuc', null, '01056');
insert into address (id, street, city, state, zip) values (8, 'Meadow Ridge', 'Mekon', null, null);
insert into address (id, street, city, state, zip) values (9, 'Monument', 'Kremenets’', null, null);
insert into address (id, street, city, state, zip) values (10, 'Delladonna', 'Tarragona', 'Cataluna', '43071');
insert into address (id, street, city, state, zip) values (11, 'Messerschmidt', 'Timiryazevo', null, null);
insert into address (id, street, city, state, zip) values (12, 'Springs', 'Krajan', null, null);
insert into address (id, street, city, state, zip) values (13, 'Village', 'Nanwai', null, null);
insert into address (id, street, city, state, zip) values (14, 'Superior', 'Jimaguayú', null, null);
insert into address (id, street, city, state, zip) values (15, 'Magdeline', 'Longhu', null, null);
insert into address (id, street, city, state, zip) values (16, 'Blaine', 'Dongjiao', null, null);
insert into address (id, street, city, state, zip) values (17, 'South', 'Dorp Tera Kora', null, null);
insert into address (id, street, city, state, zip) values (18, 'Magdeline', 'Liyuan', null, null);
insert into address (id, street, city, state, zip) values (19, 'Acker', 'Alderetes', null, '4178');
insert into address (id, street, city, state, zip) values (20, 'Fairfield', 'Cazin', null, null);
insert into address (id, street, city, state, zip) values (21, 'Troy', 'Guxian', null, null);
insert into address (id, street, city, state, zip) values (22, 'Macpherson', 'Tahara', null, '879-7305');
insert into address (id, street, city, state, zip) values (23, 'Hayes', 'Lop', null, null);
insert into address (id, street, city, state, zip) values (24, 'Onsgard', 'Västerås', 'Västmanland', '725 96');
insert into address (id, street, city, state, zip) values (25, 'International', 'Arão', 'Viana do Castelo', '4930-005');
insert into address (id, street, city, state, zip) values (26, 'Mesta', 'Maguilling', null, '3527');
insert into address (id, street, city, state, zip) values (27, 'Brickson Park', 'Kimil’tey', null, '665375');
insert into address (id, street, city, state, zip) values (28, 'Arizona', 'Boulder', 'Colorado', '80305');
insert into address (id, street, city, state, zip) values (29, 'Namekagon', 'Bojongsari', null, null);
insert into address (id, street, city, state, zip) values (30, 'Beilfuss', 'Cruz das Almas', null, '44380-000');
insert into address (id, street, city, state, zip) values (31, 'Orin', 'Kangping', null, null);
insert into address (id, street, city, state, zip) values (32, 'Mosinee', 'Samboan', null, '6027');
insert into address (id, street, city, state, zip) values (33, 'Straubel', 'Bordeaux', 'Aquitaine', '33070 CEDEX');
insert into address (id, street, city, state, zip) values (34, 'Carpenter', 'Panambi', null, '98280-000');
insert into address (id, street, city, state, zip) values (35, 'Meadow Ridge', 'Tanushimarumachi-toyoki', null, '839-1344');
insert into address (id, street, city, state, zip) values (36, 'Buell', 'Maymana', null, null);
insert into address (id, street, city, state, zip) values (37, 'Manley', 'Melaka', 'Melaka', '75518');
insert into address (id, street, city, state, zip) values (38, 'Badeau', 'Az Zarqā', null, null);
insert into address (id, street, city, state, zip) values (39, 'Kedzie', 'Lingion', null, '8708');
insert into address (id, street, city, state, zip) values (40, 'Ridgeway', 'Ouijjane', null, null);
insert into address (id, street, city, state, zip) values (41, 'Petterle', 'Huangcaotuo', null, null);
insert into address (id, street, city, state, zip) values (42, 'Stang', 'Lidun', null, null);
insert into address (id, street, city, state, zip) values (43, 'Mallard', 'Huwan', null, null);
insert into address (id, street, city, state, zip) values (44, 'Lindbergh', 'Jiuxian', null, null);
insert into address (id, street, city, state, zip) values (45, 'Westerfield', 'Riangkroko', null, null);
insert into address (id, street, city, state, zip) values (46, 'Petterle', 'Igarapava', null, '14540-000');
insert into address (id, street, city, state, zip) values (47, 'Crescent Oaks', 'Zhongdong', null, null);
insert into address (id, street, city, state, zip) values (48, 'Jenna', 'Yangiobod', null, null);
insert into address (id, street, city, state, zip) values (49, 'Delladonna', 'Xiawuqi', null, null);
insert into address (id, street, city, state, zip) values (50, 'Troy', 'Jianshe', null, null);
insert into address (id, street, city, state, zip) values (51, 'Alpine', 'Numan', null, null);
insert into address (id, street, city, state, zip) values (52, 'Nobel', 'Loures', 'Lisboa', '2670-335');
insert into address (id, street, city, state, zip) values (53, 'Donald', 'Sibaté', null, '111971');
insert into address (id, street, city, state, zip) values (54, 'Commercial', 'Kampungruweh', null, null);
insert into address (id, street, city, state, zip) values (55, 'Manley', 'Shiyaogou', null, null);
insert into address (id, street, city, state, zip) values (56, 'Valley Edge', 'Longhuashan', null, null);
insert into address (id, street, city, state, zip) values (57, 'Eastwood', 'Hule', null, null);
insert into address (id, street, city, state, zip) values (58, 'Cottonwood', 'Iwanuma', null, '299-4336');
insert into address (id, street, city, state, zip) values (59, 'Village Green', 'Stakhanov', null, null);
insert into address (id, street, city, state, zip) values (60, 'Roth', 'Zhuangtou', null, null);
insert into address (id, street, city, state, zip) values (61, 'Mallard', 'Jiangcun', null, null);
insert into address (id, street, city, state, zip) values (62, 'Hoepker', 'Salinas', 'California', '93907');
insert into address (id, street, city, state, zip) values (63, 'Warner', 'Ust’-Abakan', null, '163028');
insert into address (id, street, city, state, zip) values (64, 'Kedzie', 'Dupi', null, null);
insert into address (id, street, city, state, zip) values (65, 'Toban', 'Adelaide', 'South Australia', '5839');
insert into address (id, street, city, state, zip) values (66, 'Main', 'Loshnitsa', null, null);
insert into address (id, street, city, state, zip) values (67, 'Birchwood', 'Överkalix', 'Norrbotten', '956 93');
insert into address (id, street, city, state, zip) values (68, 'Eggendart', 'Bianxiong', null, null);
insert into address (id, street, city, state, zip) values (69, 'Veith', 'Kebunkelapa', null, null);
insert into address (id, street, city, state, zip) values (70, 'Truax', 'Nanterre', 'Île-de-France', '92885 CEDEX 9');
insert into address (id, street, city, state, zip) values (71, 'Judy', 'Keetmanshoop', null, null);
insert into address (id, street, city, state, zip) values (72, 'Golf View', 'Kawm Ḩamādah', null, null);
insert into address (id, street, city, state, zip) values (73, 'Lotheville', 'Omsk', null, '644000');
insert into address (id, street, city, state, zip) values (74, 'Coolidge', 'Campaka', null, null);
insert into address (id, street, city, state, zip) values (75, 'Thompson', 'Sydney', 'New South Wales', '1109');
insert into address (id, street, city, state, zip) values (76, 'Orin', 'Asikkala', null, '17320');
insert into address (id, street, city, state, zip) values (77, 'Mayer', 'San Bernardino', null, null);
insert into address (id, street, city, state, zip) values (78, 'Kingsford', 'Taipingxu', null, null);
insert into address (id, street, city, state, zip) values (79, 'Novick', 'Dean', 'England', 'OX7');
insert into address (id, street, city, state, zip) values (80, 'Nova', 'Cimaung Kidul', null, null);
insert into address (id, street, city, state, zip) values (81, 'Bartillon', 'Skien', 'Telemark', '3736');
insert into address (id, street, city, state, zip) values (82, 'Onsgard', 'Ciénaga de Oro', null, '232538');
insert into address (id, street, city, state, zip) values (83, 'Bunting', 'Sneek', 'Provincie Friesland', '8604');
insert into address (id, street, city, state, zip) values (84, 'Bartelt', 'Chongjin', null, null);
insert into address (id, street, city, state, zip) values (85, 'Logan', 'Olyka', null, null);
insert into address (id, street, city, state, zip) values (86, 'Lerdahl', 'Huangjin', null, null);
insert into address (id, street, city, state, zip) values (87, 'Glendale', 'Webuye', null, null);
insert into address (id, street, city, state, zip) values (88, 'John Wall', 'Duas Igrejas', 'Bragança', '5210-046');
insert into address (id, street, city, state, zip) values (89, 'Merchant', 'Ravānsar', null, null);
insert into address (id, street, city, state, zip) values (90, 'Hudson', 'Guancangping', null, null);
insert into address (id, street, city, state, zip) values (91, 'Hintze', 'Vihti', null, '03400');
insert into address (id, street, city, state, zip) values (92, 'Arapahoe', 'Santa Lucía', null, '5413');
insert into address (id, street, city, state, zip) values (93, 'Ryan', 'Rzepiennik Strzyżewski', null, '33-163');
insert into address (id, street, city, state, zip) values (94, 'Buhler', 'Tuamese', null, null);
insert into address (id, street, city, state, zip) values (95, 'Larry', 'Pandansari', null, null);
insert into address (id, street, city, state, zip) values (96, 'Sherman', 'San Onofre', null, '707018');
insert into address (id, street, city, state, zip) values (97, 'Farmco', 'Järfälla', 'Stockholm', '175 49');
insert into address (id, street, city, state, zip) values (98, 'Morning', 'Jiancheng', null, null);
insert into address (id, street, city, state, zip) values (99, 'Doe Crossing', 'Trai Ngau', null, null);
insert into address (id, street, city, state, zip) values (100, 'Magdeline', 'Malhiao', null, '6032');
